/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    // Disable Oxide minifier — v4.2.2 native binary emits invalid UTF-8 bytes
    // for arbitrary-value classes with high-byte RGB channels (e.g. rgba(150,…))
    // which causes PostCSS to throw "Missed semicolon" during production builds.
    "@tailwindcss/postcss": {
      optimize: false,
    },
    // Expand CSS nesting generated by Tailwind v4 (color-mix @supports blocks)
    // so older PostCSS parsers / Turbopack can handle them
    "postcss-nesting": {},
  },
};

export default config;
