// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/academy" | "/academy/[slug]" | "/account" | "/account/billing" | "/admin" | "/admin/onboarding" | "/cart" | "/case-studies" | "/checkout" | "/contact" | "/help" | "/help/[slug]" | "/how-it-works" | "/invoice/[number]" | "/journal" | "/journal/[slug]" | "/login" | "/onboarding" | "/pricing" | "/privacy" | "/products" | "/products/[productId]" | "/return-policy" | "/shipping-policy" | "/signup" | "/store/[handle]" | "/store/[handle]/[productId]" | "/store/[handle]/drop/[slug]" | "/studio" | "/studio/[productId]" | "/terms" | "/track"
type AppRouteHandlerRoutes = "/api/account/orders" | "/api/admin/coupons" | "/api/admin/milestone" | "/api/admin/orders" | "/api/admin/product-gates" | "/api/admin/refund" | "/api/admin/studio-products" | "/api/admin/studio-settings" | "/api/admin/tracking" | "/api/admin/users" | "/api/admin/wallet" | "/api/billing/usage" | "/api/branding" | "/api/contact" | "/api/coupon" | "/api/create-order" | "/api/cron/monthly-invoices" | "/api/customers" | "/api/dashboard" | "/api/designs" | "/api/drops" | "/api/drops/[id]" | "/api/drops/products" | "/api/drops/public" | "/api/drops/stats" | "/api/drops/waitlist" | "/api/email/order-confirmation" | "/api/invoices" | "/api/invoices/[id]" | "/api/manual-orders" | "/api/organizations" | "/api/organizations/[slug]" | "/api/organizations/[slug]/dashboard" | "/api/organizations/[slug]/members" | "/api/organizations/[slug]/stores" | "/api/profile" | "/api/profile/bank-account" | "/api/referrals" | "/api/save-order" | "/api/shipping-rates" | "/api/shopify/auth" | "/api/shopify/callback" | "/api/shopify/connect" | "/api/shopify/orders" | "/api/shopify/orders/confirm" | "/api/shopify/push-product" | "/api/shopify/sku-mappings" | "/api/shopify/webhooks" | "/api/store-upload" | "/api/stores" | "/api/stores/[handle]" | "/api/stores/[handle]/products" | "/api/stores/payout-stats" | "/api/studio-products" | "/api/studio-settings" | "/api/subscribe" | "/api/subscribe/cancel" | "/api/subscribe/verify" | "/api/track" | "/api/upload-design" | "/api/wallet" | "/api/wallet/add-credit" | "/api/wallet/debit-for-order" | "/api/wallet/verify-payment" | "/api/webhooks/razorpay"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/academy": {}
  "/academy/[slug]": { "slug": string; }
  "/account": {}
  "/account/billing": {}
  "/admin": {}
  "/admin/onboarding": {}
  "/api/account/orders": {}
  "/api/admin/coupons": {}
  "/api/admin/milestone": {}
  "/api/admin/orders": {}
  "/api/admin/product-gates": {}
  "/api/admin/refund": {}
  "/api/admin/studio-products": {}
  "/api/admin/studio-settings": {}
  "/api/admin/tracking": {}
  "/api/admin/users": {}
  "/api/admin/wallet": {}
  "/api/billing/usage": {}
  "/api/branding": {}
  "/api/contact": {}
  "/api/coupon": {}
  "/api/create-order": {}
  "/api/cron/monthly-invoices": {}
  "/api/customers": {}
  "/api/dashboard": {}
  "/api/designs": {}
  "/api/drops": {}
  "/api/drops/[id]": { "id": string; }
  "/api/drops/products": {}
  "/api/drops/public": {}
  "/api/drops/stats": {}
  "/api/drops/waitlist": {}
  "/api/email/order-confirmation": {}
  "/api/invoices": {}
  "/api/invoices/[id]": { "id": string; }
  "/api/manual-orders": {}
  "/api/organizations": {}
  "/api/organizations/[slug]": { "slug": string; }
  "/api/organizations/[slug]/dashboard": { "slug": string; }
  "/api/organizations/[slug]/members": { "slug": string; }
  "/api/organizations/[slug]/stores": { "slug": string; }
  "/api/profile": {}
  "/api/profile/bank-account": {}
  "/api/referrals": {}
  "/api/save-order": {}
  "/api/shipping-rates": {}
  "/api/shopify/auth": {}
  "/api/shopify/callback": {}
  "/api/shopify/connect": {}
  "/api/shopify/orders": {}
  "/api/shopify/orders/confirm": {}
  "/api/shopify/push-product": {}
  "/api/shopify/sku-mappings": {}
  "/api/shopify/webhooks": {}
  "/api/store-upload": {}
  "/api/stores": {}
  "/api/stores/[handle]": { "handle": string; }
  "/api/stores/[handle]/products": { "handle": string; }
  "/api/stores/payout-stats": {}
  "/api/studio-products": {}
  "/api/studio-settings": {}
  "/api/subscribe": {}
  "/api/subscribe/cancel": {}
  "/api/subscribe/verify": {}
  "/api/track": {}
  "/api/upload-design": {}
  "/api/wallet": {}
  "/api/wallet/add-credit": {}
  "/api/wallet/debit-for-order": {}
  "/api/wallet/verify-payment": {}
  "/api/webhooks/razorpay": {}
  "/cart": {}
  "/case-studies": {}
  "/checkout": {}
  "/contact": {}
  "/help": {}
  "/help/[slug]": { "slug": string; }
  "/how-it-works": {}
  "/invoice/[number]": { "number": string; }
  "/journal": {}
  "/journal/[slug]": { "slug": string; }
  "/login": {}
  "/onboarding": {}
  "/pricing": {}
  "/privacy": {}
  "/products": {}
  "/products/[productId]": { "productId": string; }
  "/return-policy": {}
  "/shipping-policy": {}
  "/signup": {}
  "/store/[handle]": { "handle": string; }
  "/store/[handle]/[productId]": { "handle": string; "productId": string; }
  "/store/[handle]/drop/[slug]": { "handle": string; "slug": string; }
  "/studio": {}
  "/studio/[productId]": { "productId": string; }
  "/terms": {}
  "/track": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
