// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/academy/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/academy/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy">> = Specific
  const handler = {} as typeof import("../../../src/app/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/account/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/account/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/affiliate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate">> = Specific
  const handler = {} as typeof import("../../../src/app/affiliate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/become-a-partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/become-a-partner">> = Specific
  const handler = {} as typeof import("../../../src/app/become-a-partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/bulk-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bulk-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/bulk-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../../src/app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/help/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/help/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/how-it-works">> = Specific
  const handler = {} as typeof import("../../../src/app/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/invoice/[number]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/[number]">> = Specific
  const handler = {} as typeof import("../../../src/app/invoice/[number]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/journal/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/journal/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/journal/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/journal">> = Specific
  const handler = {} as typeof import("../../../src/app/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/press/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/press">> = Specific
  const handler = {} as typeof import("../../../src/app/press/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/products/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[productId]">> = Specific
  const handler = {} as typeof import("../../../src/app/products/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quality">> = Specific
  const handler = {} as typeof import("../../../src/app/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/return-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/return-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/return-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shipping-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipping-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/shipping-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sitemap-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sitemap-page">> = Specific
  const handler = {} as typeof import("../../../src/app/sitemap-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/size-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/size-guide">> = Specific
  const handler = {} as typeof import("../../../src/app/size-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/store/[handle]/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/[handle]/[productId]">> = Specific
  const handler = {} as typeof import("../../../src/app/store/[handle]/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/store/[handle]/drop/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/[handle]/drop/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/store/[handle]/drop/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/store/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/[handle]">> = Specific
  const handler = {} as typeof import("../../../src/app/store/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/[productId]">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sustainability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sustainability">> = Specific
  const handler = {} as typeof import("../../../src/app/sustainability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/talk-to-sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/talk-to-sales">> = Specific
  const handler = {} as typeof import("../../../src/app/talk-to-sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track">> = Specific
  const handler = {} as typeof import("../../../src/app/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/affiliates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/affiliates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/affiliates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/coupons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coupons">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/coupons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/milestone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/milestone">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/milestone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/product-gates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/product-gates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/product-gates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/refund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/refund">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/refund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/studio-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/studio-products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/studio-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/studio-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/studio-settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/studio-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/tracking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/tracking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/wallet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wallet">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/wallet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/affiliate/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/apply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/affiliate/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/affiliate/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/affiliate/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/affiliate/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affiliate/track">> = Specific
  const handler = {} as typeof import("../../../src/app/api/affiliate/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/billing/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/usage">> = Specific
  const handler = {} as typeof import("../../../src/app/api/billing/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/branding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branding">> = Specific
  const handler = {} as typeof import("../../../src/app/api/branding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/coupon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coupon">> = Specific
  const handler = {} as typeof import("../../../src/app/api/coupon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/create-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/create-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/monthly-invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/monthly-invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/monthly-invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/designs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/designs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/designs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drops/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drops/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drops/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drops/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drops/products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drops/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drops/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drops/public">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drops/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drops">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drops/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drops/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drops/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drops/waitlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drops/waitlist">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drops/waitlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email/order-confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/order-confirmation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email/order-confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invoices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invoices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/manual-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manual-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/manual-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[slug]/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[slug]/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[slug]/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[slug]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[slug]/members">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[slug]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/[slug]/stores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations/[slug]/stores">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/[slug]/stores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/organizations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organizations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/organizations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/profile/bank-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/bank-account">> = Specific
  const handler = {} as typeof import("../../../src/app/api/profile/bank-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/referrals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referrals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/referrals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/save-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/save-order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/save-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shipping-rates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shipping-rates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shipping-rates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/connect">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/orders/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/orders/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/orders/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/push-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/push-product">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/push-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/sku-mappings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/sku-mappings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/sku-mappings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shopify/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shopify/webhooks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shopify/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/store-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store-upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/store-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stores/[handle]/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stores/[handle]/products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stores/[handle]/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stores/[handle]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stores/[handle]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stores/[handle]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stores/payout-stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stores/payout-stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stores/payout-stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stores">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/studio-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio-products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/studio-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/studio-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/studio-settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/studio-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscribe/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscribe/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/subscribe/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/subscribe/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../../src/app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/upload-design/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload-design">> = Specific
  const handler = {} as typeof import("../../../src/app/api/upload-design/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wallet/add-credit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/add-credit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wallet/add-credit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wallet/debit-for-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/debit-for-order">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wallet/debit-for-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wallet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wallet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wallet/verify-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/verify-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wallet/verify-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/razorpay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/razorpay">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/razorpay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
